### ISSUE TITLE
The website doesnt work 

### ISSUE THREAD

**Issue by VrindavanSanap** [janosh/geometric-bayes#8]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/66788089/213460998-7931d22e-8f64-4ba2-a992-17ad713f8682.png">

**Comment by janosh** [comment]
Thanks for hint. Should be fixed now.

Fair warning though, I was planning to merge this repo as a blog post into https://github.com/janosh/blog anyway in the near future.
